public  class Adress {
public void homeAdress(){
      string myName = 'Roya';
      system.debug('myName is ' + myname);

      integer numberOfFamilyMember = 4;
      system.debug ('numberOfFamilyMember');

      string houseName = 'Aylin';
      system.debug('houseName');

      string houseNumber = '2002';
      system.debug(houseNumber);
       string cityName = 'Dallas';
       system.debug(cityName);

       string countryIsocode =  'US';
       system.debug('countryIsocode');

       integer zipCode = 75098;
       system.debug(zipCode);

       boolean isYourhome = true;
       system.debug(isYourhome);
       


    }
    

    }

